imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: '@AppBundle/Resources/config/services.yml'}
    - { resource: '@AppBundle/Resources/config/admin.yml'}

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
      owner_url: http://www.new.by

# Assetic Configuration
assetic:
    node: /usr/bin/node
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ApplicationAvanzuAdminThemeBundle, ApplicationSonataAdminBundle ]
    assets:
      application_sonata_admin:
          inputs:
              - '@AppBundle/Resources/public/css/*'
              - '@AppBundle/Resources/public/js/*'
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        uglifycss:
            bin: /usr/local/lib/node_modules/uglifycss/uglifycss
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
              json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
    encryption: ssl

fos_user:
  profile:  # Authentication Form
          form:
              type:               fos_user_profile
              handler:            fos_user.profile.form.handler.default
              name:               fos_user_profile_form
              validation_groups:  [Authentication] # Please note : this is not the default value

  from_email: # global email address for fosuserbundle
      address:        carwest@tut.by
      sender_name:    knocker
  db_driver:  orm # can be orm or odm
  firewall_name:  main
  user_class:  Application\Sonata\UserBundle\Entity\User

  group:
    group_class:  Application\Sonata\UserBundle\Entity\Group
    group_manager: sonata.user.orm.group_manager

  service:
    user_manager: sonata.user.orm.user_manager
    mailer: fos_user.mailer.twig_swift

  registration:
    confirmation:
      enabled: true
      from_email: # Use this node only if you don't want the global email address for the confirmation email
          address:        carwest@tut.by
          sender_name:    knocker
      template:   ApplicationSonataUserBundle:Registration:email.txt.twig
  resetting:
    token_ttl: 86400
    email:
        from_email: # Use this node only if you don't want the global email address for the resetting email
          address:        carwest@tut.by
          sender_name:    knocker
        template:   FOSUserBundle:Resetting:email.txt.twig
sonata_admin:
    persist_filters: true
    dashboard:
      groups:
        app.service:
          label: Услуги
          icon: '<i class="fa fa-th"></i>'
          roles: [ROLE_ADMIN]
        app.tariff:
          label: Тарифы
          icon: '<i class="fa fa-dollar"></i>'
          roles: [ROLE_ADMIN]
        app.region:
          label: Регионы и валюты
          icon: '<i class="fa fa-ruble"></i>'
          roles: [ROLE_ADMIN]
        sonata_user:
          label: Пользователи
          icon: ~
          roles: [ROLE_ADMIN]
    title:  KNOCKER
    title_logo:           bundles/app/image/logo.png
    options:
      title_mode: "single_image"
    templates:
        layout: ApplicationSonataAdminBundle::standard_layout.html.twig
    assets:
      stylesheets:
            - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/_all-skins.min.css
            - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css


sonata_block:
  default_contexts: [cms]
  blocks:
    # Enable the SonataAdminBundle block
    sonata.admin.block.admin_list:
      contexts:  [admin]
    sonata.user.block.menu: ~
    sonata.block.service.text: ~


sonata_user:
  #security_acl: true # Uncomment for ACL support
  manager_type: orm # can be orm or mongodb
  admin:
    user:
      class: Application\Sonata\UserBundle\Admin\UserAdmin
      translation:  SonataUserBundle
  profile:
    form:
        type:               application_sonata_user_profile
        handler:            sonata.user.profile.form.handler.default
        name:               sonata_user_profile_form
        validation_groups:  [Profile]
    dashboard:
      blocks:
        - { position: left, type: sonata.block.service.text, settings: { content: "<h2>Правила добавления ссылок на сайт</h2> Ссылка должна быть на следующий url: new.by/ключ доступа (см. выше)/имя каталога"} }
    menu:
      - { route: 'sonata_user_profile_show', label: 'sonata_profile_title', domain: 'SonataUserBundle'}
      - { route: 'sonata_user_profile_edit', label: 'link_edit_profile', domain: 'SonataUserBundle'}
      - { route: 'profile_services', label: 'Услуги'}
      - { route: 'fos_user_security_logout', label: 'layout.logout', domain: 'FOSUserBundle'}

sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        agreement:
            providers:
                - sonata.media.provider.image
            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 2000 , quality: 100}
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false