services:
#    booking.example:
#        class: BookingBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

  booking.manager:
    class: BookingBundle\Entity\BookingManager
    arguments: [%booking.class%, '@doctrine']