services:
  app.service.admin:
    class: AppBundle\Admin\ServiceAdmin
    arguments: [~, AppBundle\Entity\Service, ~]
    tags:
        - { name: sonata.admin, manager_type: orm, group: app.service, label: Услуги }