services:
  app.knocker_role_builder:
    class: AppBundle\Roles\KnockerRoleBuilder
    arguments: [@doctrine.orm.entity_manager]

  app.booking.create.listener:
    class: AppBundle\EventListeners\CreateBookingListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
        - { name: kernel.event_listener, event: booking.create }

  avanzu.admin.lte.sidebar.menu.listener:
    class: AppBundle\EventListeners\AvanzuAdminLTEListener
    arguments: [@translator]
    tags:
        - {name: kernel.event_listener, event: theme.sidebar_setup_menu}

  app.form.type.booking:
    class: AppBundle\Form\Type\BookingType
    tags:
        - { name: form.type, alias: booking_form }

  app.factory:
    class: AppBundle\Factory\Factory
    arguments: ['@doctrine.orm.entity_manager']

  security.access.booking_voter:
      class:      AppBundle\Security\Authorization\Voter\BookingVoter
      public:     false
      tags:
          - { name: security.voter }