services:
  app.knocker_role_builder:
    class: AppBundle\Roles\KnockerRoleBuilder

  app.count.create.listener:
    class: AppBundle\EventListeners\CreateCountListener
    arguments: [@doctrine.orm.entity_manager]
    tags:
        - { name: kernel.event_listener, event: count.create }

  avanzu.admin.lte.sidebar.menu.listener:
    class: AppBundle\EventListeners\AvanzuAdminLTEListener
    arguments: [@translator]
    tags:
        - {name: kernel.event_listener, event: theme.sidebar_setup_menu}