<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var string $userKey;
     */
    protected $userKey;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set userKey
     *
     *
     * @return User
     */
    public function setUserKey()
    {
        $this->userKey = sha1($this->username);

        return $this;
    }

    /**
     * Get userKey
     *
     * @return string
     */
    public function getUserKey()
    {
        return $this->userKey;
    }

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $counts;


    /**
     * Add count
     *
     * @param \AppBundle\Entity\Count $count
     *
     * @return User
     */
    public function addCount(\AppBundle\Entity\Count $count)
    {
        $count->setUser($this);
        $this->counts[] = $count;

        return $this;
    }

    /**
     * Remove count
     *
     * @param \AppBundle\Entity\Count $count
     */
    public function removeCount(\AppBundle\Entity\Count $count)
    {
        $this->counts->removeElement($count);
    }

    /**
     * Get counts
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCounts()
    {
        return $this->counts;
    }
}
